pipeline {
    agent {
        label 'agent'
    }
  
    stages { 
        stage("checkout scm") {
            steps {
                git url:'https://github.com/PriyeshPandey07/Jenkins-Docker-project.git', credentialsId: 'git', branch: 'Dockercomapose'
            }
        }
        stage("build Image") { 
            steps {

                sh "docker build -t myphpimg:latest ."
            }
        }
        stage("Container Create") {
            steps {
                sh "docker-compose up -d "
            }
        }
    }
}
